# Generated by Django 4.2.6 on 2023-10-28 16:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ComponenteProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CODIGO', models.CharField(max_length=50, unique=True)),
                ('NOMBRE', models.CharField(max_length=255)),
                ('DESCRIPCION', models.TextField(blank=True, null=True)),
                ('PRECIO_COMPRA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('PRECIO_VENTA', models.DecimalField(decimal_places=2, max_digits=10)),
                ('STOCK', models.PositiveIntegerField(default=0)),
                ('PARA_FABRICACION', models.BooleanField(default=False)),
                ('COMPONENTES', models.ManyToManyField(blank=True, through='Producto.ComponenteProducto', to='Producto.producto')),
            ],
        ),
        migrations.AddField(
            model_name='componenteproducto',
            name='producto_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_componente', to='Producto.producto'),
        ),
        migrations.AddField(
            model_name='componenteproducto',
            name='producto_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='producto_principal', to='Producto.producto'),
        ),
    ]
