# Generated by Django 4.2.6 on 2023-10-28 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0002_producto_activo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='CODIGO',
            new_name='codigo',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='COMPONENTES',
            new_name='componentes',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='DESCRIPCION',
            new_name='descripcion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='NOMBRE',
            new_name='nombre',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='PARA_FABRICACION',
            new_name='para_fabricacion',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='PRECIO_COMPRA',
            new_name='precio_compra',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='PRECIO_VENTA',
            new_name='precio_venta',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='STOCK',
            new_name='stock',
        ),
    ]
