# Generated by Django 4.2.6 on 2023-10-30 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0003_rename_codigo_producto_codigo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='tiene_descuento',
            field=models.BooleanField(default=False),
        ),
    ]
