# Generated by Django 4.2.5 on 2023-11-08 02:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Producto', '0005_transaccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenteproducto',
            name='producto_componente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_asociados', to='Producto.producto'),
        ),
        migrations.AlterField(
            model_name='componenteproducto',
            name='producto_principal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='componentes_principal', to='Producto.producto'),
        ),
    ]
